services:
  - type: web
    name: keerthivasan-portfolio-api
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
